### ISSUE TITLE
Lonux suckskkdkskskksskskks

### ISSUE THREAD

**Issue by Mootbing** [notrealn/wii-tanks-clone#2]
Bindows and Mak has Unreal Wngineeeee but leenux have to buld frum sourc :((((((

**Comment by calico32** [comment]
what's the harm in building from source

if anything it's more secure :flushed:

**Comment by Mootbing** [comment]
bee cauze eye eeiz a bad end eye don't a knowie a haw

**Comment by calico32** [comment]
`yay -S unreal-engine`

or

- git clone
- ./Setup.sh
- ./GenerateProjectFiles.sh
- make

**Comment by Mootbing** [comment]
hmm. interesante mucho. I'll keep that in mind

btw did you get GH Pro from your school too?

**Comment by notrealn** [comment]
me? no. 
wiportrort? yes
also stop spreading your stupid [proprietary malware os](https://www.gnu.org/proprietary/malware-apple.html).

**Comment by Mootbing** [comment]
okie

**Comment by anchxng** [comment]
m
